### ISSUE TITLE
[FIX] nest서버 main과 dev간의 의존성 싱크 맞추기

### ISSUE THREAD

**Issue by mikekks** [sopt-makers/sopt-crew-backend#140]
## 🚀 About Issue 🚀

- nest서버 main과 dev간의 의존성 싱크 맞춰야 함.
- 시간이 급해서 일단 main에만 급하게 수정한 상태

## ✅ Todo 

- [ ] todo !

**Comment by yeseul106** [comment]
Hotfix 사항으로 develop 브랜치에서 바로 해결
